FROM oven/bun:1

WORKDIR /user/src/app

COPY  ./packages   ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json  ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend


COPY .  .

RUN bun install 
RUN bun run db:migrate

EXPOSE 3000

CMD [ "bun","run","start:backend" ]