FROM oven/bun:1

WORKDIR /user/src/app

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL


COPY  ./packages   ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json  ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install 

COPY .  .

RUN echo "DATABASE_URL=$DATABASE_URL" > ./packages/db/.env

RUN bun run db:migrate
RUN bun run build

EXPOSE 5173

CMD [ "bun","run","start:web" ]